apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-maison-multi
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # This line solves the 404 by sending requests to '/' inside your pod
    alb.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /maison
            pathType: Prefix
            backend:
              service:
                name: my-svc-maison
                port:
                  number: 80
          - path: /multi
            pathType: Prefix
            backend:
              service:
                name: my-svc-multi
                port:
                  number: 80
