apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-maison-multi
  annotations:
    # Essential for generating a public AWS URL
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Recommended for EKS: routes traffic directly to Pod IPs
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /maison
            pathType: Prefix
            backend:
              service:
                name: my-svc-maison
                port:
                  number: 80
          - path: /multi
            pathType: Prefix
            backend:
              service:
                name: my-svc-multi
                port:
                  number: 80
